#!/bin/bash

## Description: Executes Contao database migration
## Usage: migrate
## Example: "ddev migrate --no-backup"

ddev exec --dir /var/www/html/.ddev/contao vendor/bin/contao-console contao:migrate "$@"
